name: pytorch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://mirrors.aliyun.com/anaconda/pkgs/main/
  - https://mirrors.aliyun.com/anaconda/pkgs/free/
  - https://mirrors.aliyun.com/anaconda/cloud/conda-forge/
  - https://mirrors.aliyun.com/anaconda/cloud/pytorch/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - array-api-compat=1.8=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - hdf5=1.10.6=h3ffc7dd_1
  - idna=3.7=py39h06a4308_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - jinja2=3.1.4=py39h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py39h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py39h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_0
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h5eee18b_0
  - mkl_random=1.2.7=py39h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numba=0.60.0=py39h6a678d5_0
  - numexpr=2.8.7=py39h85018f9_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=10.4.0=py39h5eee18b_0
  - pybind11-abi=4=hd8ed1ab_3
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=72.1.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.2=py39h5eee18b_0
  - stdlib-list=0.10.0=pyhd8ed1ab_0
  - sympy=1.13.2=py39h06a4308_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.0.0=py39
  - tzdata=2024a=h04d1e81_0
  - umap-learn=0.5.6=py39hf3d152e_1
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - abc-atlas-access==0.7.0
      - absl-py==2.3.1
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - anndata==0.10.2
      - annotated-types==0.7.0
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blosc2==2.5.1
      - boto3==1.40.30
      - botocore==1.40.30
      - cffi==1.17.1
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorcet==3.1.0
      - comm==0.2.2
      - dask==2024.8.0
      - dask-expr==1.1.10
      - dask-image==2024.5.3
      - datashader==0.16.3
      - debugpy==1.8.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distributed==2024.8.0
      - docrep==0.3.2
      - easydl==2.2.0
      - et-xmlfile==2.0.0
      - executing==2.1.0
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - gast==0.6.0
      - gensim==3.8.3
      - geojson==3.2.0
      - geometric==1.0.2
      - geopandas==1.0.1
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - gseapy==1.1.9
      - h11==0.14.0
      - h5py==3.2.0
      - harmonypy==0.0.10
      - httpcore==1.0.5
      - httpx==0.27.2
      - igraph==0.11.8
      - imageio==2.36.0
      - importlib-metadata==8.5.0
      - inflect==7.4.0
      - intel-cmplr-lib-ur==2024.2.1
      - intel-openmp==2024.2.1
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jmespath==1.0.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==3.10.0
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - libclang==18.1.1
      - locket==1.0.0
      - loompy==3.0.7
      - louvain==0.7.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - mkl==2024.2.2
      - ml-dtypes==0.5.3
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - namex==0.1.0
      - narwhals==2.5.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - numpy==1.26.4
      - numpy-groupies==0.11.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.9.0
      - omnipath==1.0.8
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - orderedset==2.0.3
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - param==2.1.1
      - parso==0.8.4
      - partd==1.4.2
      - pathlib2==2.3.7.post1
      - pexpect==4.9.0
      - pims==0.7
      - pip==25.2
      - platformdirs==4.3.6
      - plotly==6.3.0
      - pooch==1.8.2
      - pot==0.9.4
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==5.29.5
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyamg==5.2.1
      - pyarrow==18.0.0
      - pycombat==0.20
      - pycparser==2.22
      - pyct==0.5.0
      - pydantic==2.11.8
      - pydantic-core==2.33.2
      - pygments==2.18.0
      - pyogrio==0.10.0
      - pyproj==3.6.1
      - python-json-logger==2.0.7
      - python-louvain==0.1
      - pywavelets==1.6.0
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.20.0
      - s3fs==2023.6.0
      - s3transfer==0.14.0
      - scanpy==1.10.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scikit-misc==0.3.1
      - scipy==1.13.1
      - send2trash==1.8.3
      - shap==0.48.0
      - shapely==2.0.6
      - simpleitk==2.5.2
      - sinfo==0.3.4
      - slicer==0.0.8
      - slicerator==1.1.0
      - smart-open==7.0.5
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - spark-parser==1.8.9
      - sparse-dot-mkl==0.9.7
      - spatial-image==1.1.0
      - spatialdata==0.2.5.post0
      - spatialid==1.0.3
      - squidpy==1.6.1
      - stack-data==0.6.3
      - stplus==0.0.6
      - tables==3.9.2
      - tangram-sc==1.0.4
      - tbb==2021.13.1
      - tblib==3.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - texttable==1.7.0
      - tifffile==2024.8.30
      - tinycss2==1.3.0
      - tomli==2.0.1
      - toolz==1.0.0
      - torch==2.4.1+cu121
      - torch-geometric==2.5.3
      - torchaudio==2.4.1+cu121
      - torchfile==0.1.0
      - torchvision==0.19.1+cu121
      - tornado==6.4.1
      - tqdm==4.64.0
      - traitlets==5.14.3
      - typeguard==4.4.1
      - types-python-dateutil==2.9.0.20240906
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - uncompyle6==3.9.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - validators==0.34.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xarray==2024.7.0
      - xarray-dataclasses==1.8.0
      - xarray-datatree==0.0.15
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xdis==6.1.2
      - xlrd==1.2.0
      - yarl==1.11.1
      - zarr==2.18.2
      - zict==3.0.0
prefix: /opt/data/private/ywang/anaconda3/envs/pytorch
