name: ctmap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - pip=25.2
  - setuptools=72.1.0
  - wheel=0.43.0
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.3
  - h5py=3.2.0
  - scanpy=1.10.3
  - anndata=0.10.2
  - scikit-learn=1.5.2
  - joblib=1.4.2
  - threadpoolctl=3.5.0
  - matplotlib=3.9.2
  - pyparsing=3.1.2
  - cycler=0.12.1
  - kiwisolver=1.4.4
  - pillow=10.4.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-runtime=12.1.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - pip:
      - pytorch-mutex==1.0
      - torchtriton==3.0.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
